# Site settings
title:            "Stardust"
author:           Azeril
logo:             logo.png # image from https://www.flickr.com/photos/lwr/5496279831/in/set-72157594159055823
avatar:           avatar.png
favicon:          favicon.png
email:            your-email@domain.com
description: > # this means to ignore newlines until "url:"
  Roon was an excellent service, with a beautiful understated design. After
  being acquired by <a href='https://ghost.org'>Ghost</a>, the Roon theme was
  open sourced.<br> This is my Jekyll port of the Roon theme.

url:              "http://elsa.cat" # the base hostname & protocol for your site
baseurl:          "" # the subpath of your site, e.g. /blog/

twitter:          jekyllrb
github:           jekyll

permalink:        pretty
paginate:         5

# Build settings
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

gems:
  - jekyll-sitemap
  - jekyll-paginate
